services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD:?}"
      MSSQL_PID: "Express"
    volumes:
      - "volume:/var/opt/mssql"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "${DB_PASSWORD:?}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  volume:
    name: "${VOLUME:?}"
